#!/usr/bin/env bash

# Setup the markdown index file cleanly
cat <<EOF > index.md
# El Diario De Greg - Jeff Kinney

EOF

# Determine the best date tool available (prefers GNU gdate on Mac)
if command -v /opt/homebrew/bin/gdate &>/dev/null; then
    DATE_CMD="/opt/homebrew/bin/gdate"
    USE_GNU=true
elif command -v gdate &>/dev/null; then
    DATE_CMD="gdate"
    USE_GNU=true
else
    DATE_CMD="date"
    USE_GNU=false
fi

# -v reverses the sort. -z handles spaces safely by using null characters.
printf '%s\0' 20*.md | sort -z -r | while IFS= read -r -d '' file; do
    if [ -f "$file" ]; then
        # Isolate the filename from any potential path
        filename=$(basename "$file")
        
        # Extract the 8-digit date string (first 8 characters)
        clean_date="${filename:0:8}"
        
        # Format the date depending on whether we are using GNU (gdate) or BSD (date)
        if [ "$USE_GNU" = true ]; then
            strdate=$($DATE_CMD -d "$clean_date" "+%B %d, %Y")
        else
            strdate=$($DATE_CMD -f "%Y%m%d" "$clean_date" "+%B %d, %Y")
        fi
        
        echo "Processing: $file date ${strdate}"
        echo "* [Reunion ${strdate}](${file}) " >> index.md
    fi
done

cat <<EOF >> index.md

***

*This file is autogenerated.  Do not edit.*

This website was last updated on {{ site.time | date: "%B %d, %Y at %H:%M %Z" }}.

EOF

echo "Done.  Have a nice day."

